new bash conditional

diff --git a/.github/workflows/update-gbfs.yml b/.github/workflows/update-gbfs.yml
--- a/.github/workflows/update-gbfs.yml
+++ b/.github/workflows/update-gbfs.yml
@@ -29,12 +29,19 @@ jobs:
       run: |-
         git config user.name "Automated Bot"
         git config user.email "info@interline.io"
-        if [ git diff --exit-code --quiet ]; then
-          git checkout -b gbfs-$(date +%F)
-          git add -A
-          git commit -m "Updated GBFS feeds from https://github.com/NABSA/gbfs/blob/master/systems.csv at $(date -u)"
-          git push
-          gh pr create --fill-first
+        if ! git_status_output="$(git status --porcelain)"; then
+            error_code="$?"
+            echo "'git status' had an error: $error_code" 
+            exit 1
+        elif [ -z "$git_status_output" ]; then
+            echo "Working directory is clean."
+        else
+            echo "Working directory has UNCOMMITTED CHANGES."
+            git checkout -b gbfs-$(date +%F)
+            git add -A
+            git commit -m "Updated GBFS feeds from https://github.com/NABSA/gbfs/blob/master/systems.csv at $(date -u)"
+            git push
+            gh pr create --fill-first
         fi
       env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
